### ISSUE TITLE
package disappear on maven ?

### ISSUE THREAD

**Issue by chaabaj** [dwijnand/sbt-compat#15]
Hello,

It seems the package is not here on Maven. https://repo1.maven.org/maven2/com/dwijnand/
Will this package be released again  ?

**Comment by dwijnand** [comment]
as this project has different binary releases for sbt 1 and sbt 0.13, it's cross sbt version built like sbt's plugins. therefore it's released to sbt's plugin releases ivy repository:

https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.dwijnand/sbt-compat/

it was never released to maven central.

**Comment by chaabaj** [comment]
Ah ok i see my mistake then sorry
