### ISSUE TITLE
Artifact no longer found

### ISSUE THREAD

**Issue by Sciss** [dwijnand/sbt-compat#66]
could you please publish to maven central? I think old sbt plugin place bintray has disappeared. this is with sbt 1.5.5:

```
[error] Error downloading com.dwijnand:sbt-compat;sbtVersion=1.0;scalaVersion=2.12:1.2.6
[error]   Not found
[error]   Not found
[error]   not found: ~/.ivy2/local/com.dwijnand/sbt-compat/scala_2.12/sbt_1.0/1.2.6/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/dwijnand/sbt-compat_2.12_1.0/1.2.6/sbt-compat-1.2.6.pom
```

**Comment by mkurz** [comment]
+1  this needs to be published to maven central, there was a multiple hours outage of repo.scala-sbt.org just now again.
The sbt-ci-release plugin should be used, like in https://github.com/sbt/sbt-dynver/pull/242

**Comment by mkurz** [comment]
Ping @dwijnand

**Comment by mkurz** [comment]
Probably also a good idea to migrate this repo into the sbt GitHub organization and publishing under the `com.github.sbt` groupid.

**Comment by julienrf** [comment]
The artifacts have been back-published:

https://repo1.maven.org/maven2/com/dwijnand/sbt-compat_2.12_1.0/1.2.6
https://repo1.maven.org/maven2/com/dwijnand/sbt-compat_2.10_0.13/1.2.6

This issue can be closed.

**Comment by mkurz** [comment]
@julienrf nice, how did you do that? I don't see any commits etc. in this repo. Do you have access to the `com.dwijnand` groupid on maven central?

**Comment by julienrf** [comment]
Dale has write access to `com.dwijnand` on Sonatype, so he was able publish from the 1.2.6 tag (after changing a couple of things in the build definition to publish to Sonatype).
